export default {
    toolbar: {
        items: [
            "heading",
            "|",
            // "style",
            "undo",
            "redo",
            "|",
            // "fontFamily",
            // "fontSize",
            // "fontColor",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "|",
            "alignment",
            "|",
            "numberedList",
            "bulletedList",
            "|",
            // "outdent",
            // "indent",
            "|",
            "link",
            "blockQuote",
            'mediaBrowser',
            'snippetBrowser',
            "insertTable",
            "|",
            // "findAndReplace",
            // "highlight",
            // "removeFormat",
            // "specialCharacters",
            "subscript",
            "superscript",
            "horizontalLine"
        ]
    },
}
